Feature:Pay by creditcard

Lorem ipsum dolor sit amet, consectetur adipiscing elit. *Ut odio tellus, volutpat sit amet tortor ac, venenatis tempus felis.* _Pellentesque habitant morbi tristique_ senectus et netus et malesuada fames ac turpis egestas. Donec eros turpis, imperdiet sed ligula elementum, porttitor semper lacus. Duis finibus ligula mi.
**Sed vestibulum tortor consectetur sit amet.**
Ut leo ex, sodales a massa et, facilisis scelerisque ex. Duis non augue aliquet lacus euismod vestibulum eu et sem. Fusce vitae lacinia augue, quis egestas lacus. Pellentesque ut urna iaculis, pharetra magna et, luctus risus. Vestibulum lacinia vehicula nisl id mollis. Suspendisse egestas lacus purus, id imperdiet dolor facilisis vitae. Vivamus malesuada luctus faucibus. Cras non massa maximus, mattis dolor id, pulvinar dolor. Duis suscipit nisl sed mollis mollis. Vestibulum lacus massa, iaculis ut lorem id, scelerisque rutrum enim. Nulla ex ligula, feugiat eget tincidunt viverra, viverra vel orci.
Nulla vel elit eget leo lobortis placerat vel at tortor. Cras tincidunt urna arcu, vitae lacinia sapien blandit hendrerit. Suspendisse porttitor dui eget justo iaculis feugiat. Integer lectus libero, rutrum eu orci in, aliquet condimentum risus. Morbi sollicitudin diam at sollicitudin rutrum. Aenean ultrices ut dolor vel ultrices. Sed gravida dignissim massa in sollicitudin. Etiam viverra sodales erat ut porttitor. Quisque dignissim ornare turpis porttitor vestibulum. Nunc facilisis velit nisi, a lacinia odio pellentesque molestie. Nunc in lorem a lacus ornare porttitor sit amet et ex. In id scelerisque augue. Proin gravida luctus ante, vulputate blandit eros varius ac. Maecenas ipsum lectus, accumsan nec sapien id, efficitur fermentum metus.

@Browse
Scenario:Acceptance criteria one
	
 *Given* that a user is billing a client based on what's due
 *When* viewing Due for Billing items across media
 *Then* the user must be able to view the following optional column:
 * WHT code - default code applicable to this item based on tax rules
 * Tax table - tax table from which 
 
 > some quote 3
 
 *And* the user must ensure that ** Total amount receivable excludes WHT amount
